# Experiment
experiment: synflow

# Architecture
model: fc
model_class: default
seed: 42

# ===== Dataset ===== #
dataset: mnist
#name: resnet20_cifar10_wt

# ===== Learning Rate Policy ======== #
optimizer: sgd #adam #sgd #adam
lr: 0.1 # 0.005
#lr_policy: multistep_lr #cosine_lr

# ===== Network training config ===== #
post_epochs: 20
#wd: 0.0001 # 0
#momentum: 0.9
#batch_size: 128
#bias: True 

# ===== Sparsity =========== #
pruner: rand
compression: 0.5
#conv_type: SubnetConv
#bn_type: NonAffineBatchNorm
#freeze_weights: False
#weight_training: True
#prune_rate: 0.0
#init: signed_constant
#score_init: unif  #bern #unif #half #bimodal #skew # bern
#scale_fan: True


# ===== Rounding ===== #
#round: naive 
#noise: True
#noise_ratio: 0 


# ===== Regularization ===== #
#regularization: var_red_2 # var_red_2
lmbda: 0 # 0.01 #0.0001 #0.000001


# ===== Results ===== #
#result_dir: synflow_results
expid: synflow_rnd_fc_mnist_seed_42_epochs_20_compr_05


# ===== Hardware setup ===== #
workers: 1
#gpu: 0

verbose: True
