# Experiment
experiment: gem_miner

#subfolder: gemini

# === Name === #
name: FC

# === Architecture === #
arch: FC
algo: "hc"
iter_period: 3 
#iter_period: 2
hidden_size: 600
#bias: True

# ===== Dataset ===== #
#data_dir: ../data/
dataset: MNIST

# ===== Learning Rate Policy ======== #
optimizer: sgd
lr: 0.1 #0.01
lr_policy: cosine_lr #constant_lr #multistep_lr

# ===== Network training config ===== #
epochs: 15
batch_size: 128
freeze_weights: True
seed: 21
target_sparsity: 50.0
prune_type: BottomK
init: signed_constant
score_init: unif #skew #half #bimodal #skew # bern
scale_fan: False #True
#log_interval: 2
submask_size: 1
metric: "loss"
pruning_strategy: "weights"
how_to_prune: "layer"
start_from_nothing: False 
loss: "cross-entropy-loss"

# ===== Rounding ===== #
round: naive 
noise: True
noise_ratio: 0 

# ===== Quantization ===== #
hc_quantized: True
quantize_threshold: 0.5

# ===== Regularization ===== #
regularization: L2
lmbda: 0.0001 # 1e-4 #0.00005 # 5e-5

# ===== Hardware setup ===== #
workers: 1
#gpu: 0

# ===== Random subnet =========== #
random_subnet: True

skip_sanity_checks: True

skip_fine_tune: True
