# Experiment
experiment: synflow
#verbose: True 

# Architecture
model: resnet20
model_class: lottery
seed: 42

# ===== Dataset ===== #
dataset: cifar10
#name: resnet20_cifar10_wt

# ===== Learning Rate Policy ======== #
optimizer: sgd #adam #sgd #adam
#lr: 0.1 # 0.005
#lr_policy: multistep_lr #cosine_lr

# ===== Network training config ===== #
post_epochs: 100
prune_epochs: 100
#wd: 0.0001 # 0
#momentum: 0.9
#batch_size: 128
#bias: True 

# ===== Sparsity =========== #
pruner: synflow
compression: 2
#conv_type: SubnetConv
#bn_type: NonAffineBatchNorm
#freeze_weights: False
#weight_training: True
#prune_rate: 0.0
#init: signed_constant
#score_init: bern #unif #half #bimodal #skew # bern
#scale_fan: False #True


# ===== Rounding ===== #
#round: naive 
#noise: True
#noise_ratio: 0 


# ===== Regularization ===== #
#regularization: var_red_2 # var_red_2
lmbda: 0 # 0.01 #0.0001 #0.000001


# ===== Results ===== #
#result_dir: synflow_results
expid: synflow_resnet20_mnist_seed_42_epochs_100_compr_05


# ===== Hardware setup ===== #
workers: 1
#gpu: 0

