# Experiment
experiment: synflow

# Architecture
model: rnd_fc
model_class: default
seed: 21

# ===== Dataset ===== #
dataset: mnist

# ===== Learning Rate Policy ======== #
optimizer: sgd
lr: 0.1 

# ===== Network training config ===== #
post_epochs: 25
level_list: [0] # needs to be 0 to catch if statement before pruning, thus avoiding it and only training
compression_list: [0.625] #does not matter, is hard-coded in architecture, see model / layer directories

# ===== Sparsity =========== #
pruner: rand #does not matter, is hard-coded in architecture, see model / layer directories

# ===== Regularization ===== #
lmbda: 0

# ===== Results ===== #
expid: synflow_rnd_fc_mnist_seed_21_epochs_20_compr_0_625

# ===== Hardware setup ===== #
workers: 1
#gpu: 0

verbose: True
