# Experiment
experiment: synflow

# Architecture
model: fc
model_class: default
seed: 21 # 42 # 63

# ===== Dataset ===== #
dataset: mnist

# ===== Learning Rate Policy ======== #
optimizer: sgd
lr: 0.1

# ===== Network training config ===== #
post_epochs: 25
level_list: [10]
compression_list: [1.7] #[1.3] [1] [0.695] [0.3] --> [2%] [5%] [10%] [20%] [50%] sparsities

# ===== Sparsity =========== #
pruner: synflow  #rand

# ===== Regularization ===== #
lmbda: 0 

# ===== Results ===== #
expid: fc_mnist_seed_21_epochs_25_compr_1.7

# ===== Hardware setup ===== #
workers: 1
gpu: 0

verbose: True
