# Experiment
experiment: gem_miner

# Hypercube optimization
algo: 'hc'

# Architecture
arch: resnet20

# ===== Dataset ===== #
dataset: MNIST
name: resnet20_cifar10_wt

# ===== Learning Rate Policy ======== #
optimizer: sgd #adam #sgd #adam
lr: 0.1 # 0.005
lr_policy: multistep_lr #cosine_lr

# ===== Network training config ===== #
epochs: 3  #300
wd: 0.0001 # 0
momentum: 0.9
batch_size: 128
bias: True 

# ===== Sparsity =========== #
conv_type: SubnetConv
bn_type: NonAffineBatchNorm
freeze_weights: False
weight_training: True
prune_rate: 0.0
init: signed_constant
score_init: bern #unif #half #bimodal #skew # bern
scale_fan: False #True


# ===== Rounding ===== #
round: naive 
noise: True
noise_ratio: 0 


# ===== Regularization ===== #
regularization: var_red_2 # var_red_2
lmbda: 0 # 0.01 #0.0001 #0.000001


# ===== Hardware setup ===== #
workers: 1
gpu: 0

